server:
  port: 8022
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bhbh89900@gmail.com
    password: jbbwogheqiaejvqm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # 파일 업로드 용량 제한 50mb 로 늘리기
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/untact?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.sbs.untact.dto
custom:
  siteMainUri: http://localhost:8024/
  siteName: Untact
  emailFrom: Untact@localhost
  emailFromName: Untact
  genFileDirPath: C:/work/untact-file
  logging:
    dir: log
    level: debug